name: Python package

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        # Checkout the full history, rather than just the top commit,
        # so as not to confuse setuptools-scm.
        fetch-depth: 0
        # Checkout a pull request's HEAD commit instead of the merge
        # commit, so that gitlint lints the correct commit message.
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install tox tox-gh-actions
    - env:
        DOCKER_REGISTRY: "ghcr.io/${{ github.repository }}/"
        SETUPTOOLS_SCM_PRETEND_VERSION: "0.0.0dev"
      name: Test with tox
      run: tox
